// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIPKBHUQPsFq7ws8PizyGf0EOmpac3jyo',
    appId: '1:618024903102:web:ada8afec01f22e0b9c59ef',
    messagingSenderId: '618024903102',
    projectId: 'chat-app-c9cb1',
    authDomain: 'chat-app-c9cb1.firebaseapp.com',
    storageBucket: 'chat-app-c9cb1.appspot.com',
    measurementId: 'G-RM0036L3RQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxWqapV0DoU7IX_2V_XGx4SaFFjw1cFJ4',
    appId: '1:618024903102:android:b8b5b52599cc14449c59ef',
    messagingSenderId: '618024903102',
    projectId: 'chat-app-c9cb1',
    storageBucket: 'chat-app-c9cb1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdIF99x1bfMDhLc2KQ2CnzfjGQkOeL1FU',
    appId: '1:618024903102:ios:255152d6359956629c59ef',
    messagingSenderId: '618024903102',
    projectId: 'chat-app-c9cb1',
    storageBucket: 'chat-app-c9cb1.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdIF99x1bfMDhLc2KQ2CnzfjGQkOeL1FU',
    appId: '1:618024903102:ios:255152d6359956629c59ef',
    messagingSenderId: '618024903102',
    projectId: 'chat-app-c9cb1',
    storageBucket: 'chat-app-c9cb1.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCIPKBHUQPsFq7ws8PizyGf0EOmpac3jyo',
    appId: '1:618024903102:web:b7d7f681b86bbaf29c59ef',
    messagingSenderId: '618024903102',
    projectId: 'chat-app-c9cb1',
    authDomain: 'chat-app-c9cb1.firebaseapp.com',
    storageBucket: 'chat-app-c9cb1.appspot.com',
    measurementId: 'G-W6107R0G4F',
  );

}